databases:
  - name: budgetApp
    databaseName: budgetApp 
    user: tamana-Balkhi

services:
  - type: web
    name: budgetApp
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URLadd .
      
        fromDatabase:
          name: budgetApp
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false